# Generated by Django 4.1.4 on 2023-08-02 10:27

from django.db import migrations, models
import docx_editor_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('paragraph', models.TextField()),
                ('certificate_type', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('signature', models.CharField(max_length=100)),
                ('selected_template_id', models.CharField(max_length=10)),
                ('certificate_id', models.CharField(blank=True, default=docx_editor_app.models.generate_certificate_id, max_length=10, null=True)),
            ],
        ),
    ]
